version: '2'
services:
    flask:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
        depends_on:
            - mongo
    mongo:
        image: mongo


